/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ride {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'driverPhone' : [] | [string],
  'customerPhone' : string,
  'drop' : string,
  'fare' : bigint,
  'bikeNumber' : [] | [string],
  'createdAt' : bigint,
  'pickup' : string,
  'driverName' : [] | [string],
}
export interface RiderDetails {
  'licenceNumber' : string,
  'accountStatus' : string,
  'bikeNumber' : string,
  'name' : string,
  'aadhaarNumber' : string,
  'phone' : string,
  'verificationStatus' : string,
}
export interface RiderProfile {
  'status' : string,
  'name' : string,
  'totalEarnings' : bigint,
  'phone' : string,
}
export interface User {
  'id' : bigint,
  'password' : string,
  'name' : string,
  'role' : string,
  'phone' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptRide' : ActorMethod<[bigint, string, string, string], string>,
  'activateRider' : ActorMethod<[string], string>,
  'adminLogin' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelRide' : ActorMethod<[bigint], string>,
  'completeRide' : ActorMethod<[bigint, string], string>,
  'createRide' : ActorMethod<[string, string, string, string, bigint], Ride>,
  'getActiveRideForCustomer' : ActorMethod<[string], [] | [Ride]>,
  'getActiveRideForRider' : ActorMethod<[string], [] | [Ride]>,
  'getAllRiders' : ActorMethod<[], Array<RiderDetails>>,
  'getAllRides' : ActorMethod<[], Array<Ride>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPendingRides' : ActorMethod<[], Array<Ride>>,
  'getRideById' : ActorMethod<[bigint], [] | [Ride]>,
  'getRiderDetails' : ActorMethod<[string], [] | [RiderDetails]>,
  'getRiderProfile' : ActorMethod<[string], RiderProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginUser' : ActorMethod<[string, string], [] | [User]>,
  'registerRider' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'registerUser' : ActorMethod<[string, string, string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setRiderStatus' : ActorMethod<[string, string], string>,
  'suspendRider' : ActorMethod<[string], string>,
  'verifyRider' : ActorMethod<[string, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];