/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Ride = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'driverPhone' : IDL.Opt(IDL.Text),
  'customerPhone' : IDL.Text,
  'drop' : IDL.Text,
  'fare' : IDL.Nat,
  'bikeNumber' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'pickup' : IDL.Text,
  'driverName' : IDL.Opt(IDL.Text),
});
export const RiderProfile = IDL.Record({
  'status' : IDL.Text,
  'name' : IDL.Text,
  'totalEarnings' : IDL.Nat,
  'phone' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'acceptRide' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'cancelRide' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'completeRide' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'createRide' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Ride],
      [],
    ),
  'getActiveRideForCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Ride)], ['query']),
  'getActiveRideForRider' : IDL.Func([IDL.Text], [IDL.Opt(Ride)], ['query']),
  'getPendingRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
  'getRideById' : IDL.Func([IDL.Nat], [IDL.Opt(Ride)], ['query']),
  'getRiderProfile' : IDL.Func([IDL.Text], [RiderProfile], []),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(User)], ['query']),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'setRiderStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Ride = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'driverPhone' : IDL.Opt(IDL.Text),
    'customerPhone' : IDL.Text,
    'drop' : IDL.Text,
    'fare' : IDL.Nat,
    'bikeNumber' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'pickup' : IDL.Text,
    'driverName' : IDL.Opt(IDL.Text),
  });
  const RiderProfile = IDL.Record({
    'status' : IDL.Text,
    'name' : IDL.Text,
    'totalEarnings' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'acceptRide' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'cancelRide' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'completeRide' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'createRide' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Ride],
        [],
      ),
    'getActiveRideForCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Ride)],
        ['query'],
      ),
    'getActiveRideForRider' : IDL.Func([IDL.Text], [IDL.Opt(Ride)], ['query']),
    'getPendingRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
    'getRideById' : IDL.Func([IDL.Nat], [IDL.Opt(Ride)], ['query']),
    'getRiderProfile' : IDL.Func([IDL.Text], [RiderProfile], []),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(User)], ['query']),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'setRiderStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };