/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Ride = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'driverPhone' : IDL.Opt(IDL.Text),
  'customerPhone' : IDL.Text,
  'drop' : IDL.Text,
  'fare' : IDL.Nat,
  'bikeNumber' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'pickup' : IDL.Text,
  'rideStartCode' : IDL.Opt(IDL.Text),
  'driverName' : IDL.Opt(IDL.Text),
});
export const RiderDetails = IDL.Record({
  'licenceNumber' : IDL.Text,
  'accountStatus' : IDL.Text,
  'bikeNumber' : IDL.Text,
  'name' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'phone' : IDL.Text,
  'aadhaarImage' : IDL.Text,
  'verificationStatus' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'phone' : IDL.Text,
});
export const RideCustomerRequest = IDL.Record({
  'destination' : IDL.Text,
  'source' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const RiderProfile = IDL.Record({
  'status' : IDL.Text,
  'name' : IDL.Text,
  'totalEarnings' : IDL.Nat,
  'phone' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptRide' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'activateRider' : IDL.Func([IDL.Text], [IDL.Text], []),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelRide' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'completeRide' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'createRide' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Ride],
      [],
    ),
  'getActiveRideForCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Ride)], ['query']),
  'getActiveRideForRider' : IDL.Func([IDL.Text], [IDL.Opt(Ride)], ['query']),
  'getAllRiders' : IDL.Func([], [IDL.Vec(RiderDetails)], ['query']),
  'getAllRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDemoCustomers' : IDL.Func([], [IDL.Vec(RideCustomerRequest)], ['query']),
  'getPendingRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
  'getRideById' : IDL.Func([IDL.Nat], [IDL.Opt(Ride)], ['query']),
  'getRiderDetails' : IDL.Func([IDL.Text], [IDL.Opt(RiderDetails)], ['query']),
  'getRiderProfile' : IDL.Func([IDL.Text], [RiderProfile], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(User)], ['query']),
  'registerRider' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setRiderStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'startRideWithCode' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Text], []),
  'suspendRider' : IDL.Func([IDL.Text], [IDL.Text], []),
  'uploadRiderAadhaarImage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'verifyRider' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Ride = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'driverPhone' : IDL.Opt(IDL.Text),
    'customerPhone' : IDL.Text,
    'drop' : IDL.Text,
    'fare' : IDL.Nat,
    'bikeNumber' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'pickup' : IDL.Text,
    'rideStartCode' : IDL.Opt(IDL.Text),
    'driverName' : IDL.Opt(IDL.Text),
  });
  const RiderDetails = IDL.Record({
    'licenceNumber' : IDL.Text,
    'accountStatus' : IDL.Text,
    'bikeNumber' : IDL.Text,
    'name' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'phone' : IDL.Text,
    'aadhaarImage' : IDL.Text,
    'verificationStatus' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RideCustomerRequest = IDL.Record({
    'destination' : IDL.Text,
    'source' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RiderProfile = IDL.Record({
    'status' : IDL.Text,
    'name' : IDL.Text,
    'totalEarnings' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptRide' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'activateRider' : IDL.Func([IDL.Text], [IDL.Text], []),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelRide' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'completeRide' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'createRide' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Ride],
        [],
      ),
    'getActiveRideForCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Ride)],
        ['query'],
      ),
    'getActiveRideForRider' : IDL.Func([IDL.Text], [IDL.Opt(Ride)], ['query']),
    'getAllRiders' : IDL.Func([], [IDL.Vec(RiderDetails)], ['query']),
    'getAllRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDemoCustomers' : IDL.Func(
        [],
        [IDL.Vec(RideCustomerRequest)],
        ['query'],
      ),
    'getPendingRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
    'getRideById' : IDL.Func([IDL.Nat], [IDL.Opt(Ride)], ['query']),
    'getRiderDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RiderDetails)],
        ['query'],
      ),
    'getRiderProfile' : IDL.Func([IDL.Text], [RiderProfile], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(User)], ['query']),
    'registerRider' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setRiderStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'startRideWithCode' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'suspendRider' : IDL.Func([IDL.Text], [IDL.Text], []),
    'uploadRiderAadhaarImage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'verifyRider' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };